project_id = "hpclzzykgxolszduecqa"

[functions.pdf-search-assistant]
verify_jwt = false

[functions.analyze-pdf-content]
verify_jwt = false

[functions.generate-diagnostic-assessment]
verify_jwt = false
